spring:
  application:
    name: smart-irrigation
  jackson:
    time-zone: Europe/Istanbul
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://smart-irrigation-db.cjaek4agg94j.eu-central-1.rds.amazonaws.com:5432/smart_irrigation
    username: irrigation_admin
    password: D#8fK4x!Rz7Lp9Wq
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

weather:
  api:
    key: a2698fa3fd2522b59c7c92c91ad1bcef
  location: Istanbul,TR